app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$setInputs(size = 12)
app$snapshot()
app$setInputs(size = 8)
app$snapshot()
app$setInputs(size = 15)
app$snapshot()
app$setInputs(size = 6)
app$snapshot()
