app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$setInputs(y = 2)
app$setInputs(y = 3)
app$setInputs(x = -1)
app$setInputs(x = -2)
app$snapshot()
app$setInputs(x = -1)
app$setInputs(x = 0)
app$setInputs(x = 5)
app$snapshot()
app$setInputs(z = 3)
app$setInputs(z = 5)
app$snapshot()
